- name: Evaluate Artemis Pod Monitor - DC A
  k8s:
    state: present
    namespace: '{{ dc_a_namespace }}'
    resource_definition: "{{ lookup('template', 'artemis-service-monitor-dc-a.yml.j2') }}"

- name: Evaluate Artemis Pod Monitor - DC B
  k8s:
    state: present
    namespace: '{{ dc_b_namespace }}'
    resource_definition: "{{ lookup('template', 'artemis-service-monitor-dc-b.yml.j2') }}"

- name: Evaluate Strimzi Pod Monitor - DC A
  k8s:
    state: present
    namespace: '{{ dc_a_namespace }}'
    resource_definition: "{{ lookup('template', 'strimzi_pod_monitor-dc-a.yml.j2') }}"

- name: Evaluate Strimzi Pod Monitor - DC B
  k8s:
    state: present
    namespace: '{{ dc_b_namespace }}'
    resource_definition: "{{ lookup('template', 'strimzi_pod_monitor-dc-b.yml.j2') }}"

- name: Get Grafana ServiceAccount
  k8s_info:
    kind: ServiceAccount
    name:  grafana-serviceaccount
    namespace: '{{ dc_a_namespace }}'
    api_version: v1
  register: r_grafana_sa
  until:
    - r_grafana_sa.resources is defined
  retries: 10
  delay: 15

- name: Loop Secrets
  include_tasks: tasks/loop_secrets.yml
  with_items: '{{ r_grafana_sa.resources[0].secrets  }}'

- name: Evaluate Grafana ServiceAccount permissons
  k8s:
    state: present
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    definition:
      metadata:
        name: thanos-metric-viewer
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-monitoring-view
      subjects:
      - kind: ServiceAccount
        name: grafana-serviceaccount
        namespace: '{{ dc_a_namespace }}'

- name: Evaluate Grafana Datasource
  k8s:
    namespace: '{{ dc_a_namespace }}'
    state: present
    resource_definition: "{{ lookup('template', 'grafana_datasource.yml.j2') }}"

- name: Evaluate Kafka Dashboard
  k8s:
    state: present
    namespace: '{{ dc_a_namespace }}'
    resource_definition: "{{ lookup('file', 'grafana_kafka_dashboard.yml') }}"

# - name: Evaluate Artemis Dashboard
#   k8s:
#     state: present
#     namespace: '{{ dc_a_namespace }}'
#     resource_definition: "{{ lookup('file', 'grafana-artemis-dashboard.yml') }}"
