- hosts: localhost
  name: Install AMQ Streams and Strimzi Data Replication Demo
  vars:
    kafka_cluster_a: my-source-cluster
    kafka_cluster_b: my-target-cluster
    artemis_cluster_a: my-source-cluster
    artemis_cluster_b: my-source-cluster
    dc_a_namespace: data-center-a
    dc_b_namespace: data-center-b
    grafana_user: admin
    grafana_password: admin
    insecure_skip_tls_verify: true
    delete_demo: false
  tasks:

    - name: Define domain
      set_fact:
        domain : "{{ server | regex_replace('https://api.') | regex_replace(':6443')   }}"

    - name: login as super user with token on OpenShift 4
      command: "oc login --token={{ token }}  --server={{ server }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
      when:
       - token is defined
       - server is defined
      ignore_errors: false
    
    - name: Evaluate Data Center A Namespace
      k8s:
        state: present
        kind: Project
        api_version: project.openshift.io/v1
        definition:
          metadata:
            name: "{{ dc_a_namespace }}"

    - name: Evaluate Data Center B Namespace
      k8s:
        state: present
        kind: Project
        api_version: project.openshift.io/v1
        definition:
          metadata:
            name: "{{ dc_b_namespace }}"

    - name: Include AMQ Streams role
      include_role:
        name: streams

    - name: Include AMQ Broker role
      include_role:
        name: amq-broker

    - name: Include Monitoring role
      include_role:
        name: monitoring
    
    
